// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// LR_each
List LR_each(List Xorg, arma::mat LogY, arma::vec Ymu, Function inner, double lambda, int Xdim_max, double R, double phi, String penalty, double gamma, double eta, int max_iter, double threshold);
RcppExport SEXP _NonEuclidReg_LR_each(SEXP XorgSEXP, SEXP LogYSEXP, SEXP YmuSEXP, SEXP innerSEXP, SEXP lambdaSEXP, SEXP Xdim_maxSEXP, SEXP RSEXP, SEXP phiSEXP, SEXP penaltySEXP, SEXP gammaSEXP, SEXP etaSEXP, SEXP max_iterSEXP, SEXP thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type Xorg(XorgSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type LogY(LogYSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Ymu(YmuSEXP);
    Rcpp::traits::input_parameter< Function >::type inner(innerSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type Xdim_max(Xdim_maxSEXP);
    Rcpp::traits::input_parameter< double >::type R(RSEXP);
    Rcpp::traits::input_parameter< double >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< String >::type penalty(penaltySEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(LR_each(Xorg, LogY, Ymu, inner, lambda, Xdim_max, R, phi, penalty, gamma, eta, max_iter, threshold));
    return rcpp_result_gen;
END_RCPP
}
// LR_GCV
List LR_GCV(List X, arma::mat LogY, List Xnew, arma::mat LogYnew, arma::vec Ymu, Function inner, arma::vec lambda_list, arma::vec Xdim_max_list, arma::vec R_list, double phi, String penalty, double gamma, int max_cv_iter, double threshold);
RcppExport SEXP _NonEuclidReg_LR_GCV(SEXP XSEXP, SEXP LogYSEXP, SEXP XnewSEXP, SEXP LogYnewSEXP, SEXP YmuSEXP, SEXP innerSEXP, SEXP lambda_listSEXP, SEXP Xdim_max_listSEXP, SEXP R_listSEXP, SEXP phiSEXP, SEXP penaltySEXP, SEXP gammaSEXP, SEXP max_cv_iterSEXP, SEXP thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type LogY(LogYSEXP);
    Rcpp::traits::input_parameter< List >::type Xnew(XnewSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type LogYnew(LogYnewSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Ymu(YmuSEXP);
    Rcpp::traits::input_parameter< Function >::type inner(innerSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type lambda_list(lambda_listSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Xdim_max_list(Xdim_max_listSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type R_list(R_listSEXP);
    Rcpp::traits::input_parameter< double >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< String >::type penalty(penaltySEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< int >::type max_cv_iter(max_cv_iterSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(LR_GCV(X, LogY, Xnew, LogYnew, Ymu, inner, lambda_list, Xdim_max_list, R_list, phi, penalty, gamma, max_cv_iter, threshold));
    return rcpp_result_gen;
END_RCPP
}
// LR_Kfold
List LR_Kfold(List X_list, List LogY_list, List Xnew_list, List LogYnew_list, List Ymu_list, Function inner, int kfold, arma::vec lambda_list, arma::vec Xdim_max_list, arma::vec R_list, double phi, String penalty, double gamma, int max_cv_iter, double threshold);
RcppExport SEXP _NonEuclidReg_LR_Kfold(SEXP X_listSEXP, SEXP LogY_listSEXP, SEXP Xnew_listSEXP, SEXP LogYnew_listSEXP, SEXP Ymu_listSEXP, SEXP innerSEXP, SEXP kfoldSEXP, SEXP lambda_listSEXP, SEXP Xdim_max_listSEXP, SEXP R_listSEXP, SEXP phiSEXP, SEXP penaltySEXP, SEXP gammaSEXP, SEXP max_cv_iterSEXP, SEXP thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type X_list(X_listSEXP);
    Rcpp::traits::input_parameter< List >::type LogY_list(LogY_listSEXP);
    Rcpp::traits::input_parameter< List >::type Xnew_list(Xnew_listSEXP);
    Rcpp::traits::input_parameter< List >::type LogYnew_list(LogYnew_listSEXP);
    Rcpp::traits::input_parameter< List >::type Ymu_list(Ymu_listSEXP);
    Rcpp::traits::input_parameter< Function >::type inner(innerSEXP);
    Rcpp::traits::input_parameter< int >::type kfold(kfoldSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type lambda_list(lambda_listSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Xdim_max_list(Xdim_max_listSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type R_list(R_listSEXP);
    Rcpp::traits::input_parameter< double >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< String >::type penalty(penaltySEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< int >::type max_cv_iter(max_cv_iterSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(LR_Kfold(X_list, LogY_list, Xnew_list, LogYnew_list, Ymu_list, inner, kfold, lambda_list, Xdim_max_list, R_list, phi, penalty, gamma, max_cv_iter, threshold));
    return rcpp_result_gen;
END_RCPP
}
// PCA_list
List PCA_list(List Xall);
RcppExport SEXP _NonEuclidReg_PCA_list(SEXP XallSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type Xall(XallSEXP);
    rcpp_result_gen = Rcpp::wrap(PCA_list(Xall));
    return rcpp_result_gen;
END_RCPP
}
// predict_PCA_list
List predict_PCA_list(List pca, List Xnew);
RcppExport SEXP _NonEuclidReg_predict_PCA_list(SEXP pcaSEXP, SEXP XnewSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type pca(pcaSEXP);
    Rcpp::traits::input_parameter< List >::type Xnew(XnewSEXP);
    rcpp_result_gen = Rcpp::wrap(predict_PCA_list(pca, Xnew));
    return rcpp_result_gen;
END_RCPP
}
// LASSO_sol
arma::mat LASSO_sol(arma::mat xy, double xx, double normxy, double lambda, double kappa, double gamma);
RcppExport SEXP _NonEuclidReg_LASSO_sol(SEXP xySEXP, SEXP xxSEXP, SEXP normxySEXP, SEXP lambdaSEXP, SEXP kappaSEXP, SEXP gammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type xy(xySEXP);
    Rcpp::traits::input_parameter< double >::type xx(xxSEXP);
    Rcpp::traits::input_parameter< double >::type normxy(normxySEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    rcpp_result_gen = Rcpp::wrap(LASSO_sol(xy, xx, normxy, lambda, kappa, gamma));
    return rcpp_result_gen;
END_RCPP
}
// LASSO_sol2
arma::mat LASSO_sol2(arma::mat xy, double xx, double normxy, double lambda, double kappa, double gamma);
RcppExport SEXP _NonEuclidReg_LASSO_sol2(SEXP xySEXP, SEXP xxSEXP, SEXP normxySEXP, SEXP lambdaSEXP, SEXP kappaSEXP, SEXP gammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type xy(xySEXP);
    Rcpp::traits::input_parameter< double >::type xx(xxSEXP);
    Rcpp::traits::input_parameter< double >::type normxy(normxySEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    rcpp_result_gen = Rcpp::wrap(LASSO_sol2(xy, xx, normxy, lambda, kappa, gamma));
    return rcpp_result_gen;
END_RCPP
}
// SCAD_sol
arma::mat SCAD_sol(arma::mat xy, double xx, double normxy, double lambda, double kappa, double gamma);
RcppExport SEXP _NonEuclidReg_SCAD_sol(SEXP xySEXP, SEXP xxSEXP, SEXP normxySEXP, SEXP lambdaSEXP, SEXP kappaSEXP, SEXP gammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type xy(xySEXP);
    Rcpp::traits::input_parameter< double >::type xx(xxSEXP);
    Rcpp::traits::input_parameter< double >::type normxy(normxySEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    rcpp_result_gen = Rcpp::wrap(SCAD_sol(xy, xx, normxy, lambda, kappa, gamma));
    return rcpp_result_gen;
END_RCPP
}
// SCAD_sol2
arma::mat SCAD_sol2(arma::mat xy, double xx, double normxy, double lambda, double kappa, double gamma);
RcppExport SEXP _NonEuclidReg_SCAD_sol2(SEXP xySEXP, SEXP xxSEXP, SEXP normxySEXP, SEXP lambdaSEXP, SEXP kappaSEXP, SEXP gammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type xy(xySEXP);
    Rcpp::traits::input_parameter< double >::type xx(xxSEXP);
    Rcpp::traits::input_parameter< double >::type normxy(normxySEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    rcpp_result_gen = Rcpp::wrap(SCAD_sol2(xy, xx, normxy, lambda, kappa, gamma));
    return rcpp_result_gen;
END_RCPP
}
// MCP_sol
arma::mat MCP_sol(arma::mat xy, double xx, double normxy, double lambda, double kappa, double gamma);
RcppExport SEXP _NonEuclidReg_MCP_sol(SEXP xySEXP, SEXP xxSEXP, SEXP normxySEXP, SEXP lambdaSEXP, SEXP kappaSEXP, SEXP gammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type xy(xySEXP);
    Rcpp::traits::input_parameter< double >::type xx(xxSEXP);
    Rcpp::traits::input_parameter< double >::type normxy(normxySEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    rcpp_result_gen = Rcpp::wrap(MCP_sol(xy, xx, normxy, lambda, kappa, gamma));
    return rcpp_result_gen;
END_RCPP
}
// MCP_sol2
arma::mat MCP_sol2(arma::mat xy, double xx, double normxy, double lambda, double kappa, double gamma);
RcppExport SEXP _NonEuclidReg_MCP_sol2(SEXP xySEXP, SEXP xxSEXP, SEXP normxySEXP, SEXP lambdaSEXP, SEXP kappaSEXP, SEXP gammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type xy(xySEXP);
    Rcpp::traits::input_parameter< double >::type xx(xxSEXP);
    Rcpp::traits::input_parameter< double >::type normxy(normxySEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    rcpp_result_gen = Rcpp::wrap(MCP_sol2(xy, xx, normxy, lambda, kappa, gamma));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_NonEuclidReg_LR_each", (DL_FUNC) &_NonEuclidReg_LR_each, 13},
    {"_NonEuclidReg_LR_GCV", (DL_FUNC) &_NonEuclidReg_LR_GCV, 14},
    {"_NonEuclidReg_LR_Kfold", (DL_FUNC) &_NonEuclidReg_LR_Kfold, 15},
    {"_NonEuclidReg_PCA_list", (DL_FUNC) &_NonEuclidReg_PCA_list, 1},
    {"_NonEuclidReg_predict_PCA_list", (DL_FUNC) &_NonEuclidReg_predict_PCA_list, 2},
    {"_NonEuclidReg_LASSO_sol", (DL_FUNC) &_NonEuclidReg_LASSO_sol, 6},
    {"_NonEuclidReg_LASSO_sol2", (DL_FUNC) &_NonEuclidReg_LASSO_sol2, 6},
    {"_NonEuclidReg_SCAD_sol", (DL_FUNC) &_NonEuclidReg_SCAD_sol, 6},
    {"_NonEuclidReg_SCAD_sol2", (DL_FUNC) &_NonEuclidReg_SCAD_sol2, 6},
    {"_NonEuclidReg_MCP_sol", (DL_FUNC) &_NonEuclidReg_MCP_sol, 6},
    {"_NonEuclidReg_MCP_sol2", (DL_FUNC) &_NonEuclidReg_MCP_sol2, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_NonEuclidReg(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
