# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

AM_each <- function(SBF_comp, Ymu, Yspace, lambda, R, penalty, gamma, phi, eta, max_iter, threshold) {
    .Call(`_HDRegMfd_AM_each`, SBF_comp, Ymu, Yspace, lambda, R, penalty, gamma, phi, eta, max_iter, threshold)
}

get_loss_CV_AM_average <- function(SBF_comp, Xnew, LogYnew, Ymu, Yspace, lambda, R, cv_type, penalty, gamma, cv_const) {
    .Call(`_HDRegMfd_get_loss_CV_AM_average`, SBF_comp, Xnew, LogYnew, Ymu, Yspace, lambda, R, cv_type, penalty, gamma, cv_const)
}

get_loss_CV_AM_integral <- function(SBF_comp, Xnew, LogYnew, Ymu, Yspace, lambda, R, cv_type, penalty, gamma, cv_const) {
    .Call(`_HDRegMfd_get_loss_CV_AM_integral`, SBF_comp, Xnew, LogYnew, Ymu, Yspace, lambda, R, cv_type, penalty, gamma, cv_const)
}

AM_CBS_GCV <- function(X, LogY, Xnew, LogYnew, Ymu, Yspace, bandwidths_mat, grids, weights, lambda_list, Xdim_max_list, R_list, index_mat, cv_type = "AIC", penalty = "LASSO", gamma = 0, degree = 0L, Kdenom_method = "numeric", cv_const = 2.0, max_cv_iter = 20L, threshold = 1e-10) {
    .Call(`_HDRegMfd_AM_CBS_GCV`, X, LogY, Xnew, LogYnew, Ymu, Yspace, bandwidths_mat, grids, weights, lambda_list, Xdim_max_list, R_list, index_mat, cv_type, penalty, gamma, degree, Kdenom_method, cv_const, max_cv_iter, threshold)
}

AM_CBS_kfold <- function(X_list, LogY_list, Xnew_list, LogYnew_list, Ymu_list, Yspace, kfold, bandwidths_mat, grids, weights, lambda_list, Xdim_max_list, R_list, index_mat, cv_type = "AIC", penalty = "LASSO", gamma = 0, degree = 0L, Kdenom_method = "numeric", cv_const = 2.0, max_cv_iter = 20L, threshold = 1e-10) {
    .Call(`_HDRegMfd_AM_CBS_kfold`, X_list, LogY_list, Xnew_list, LogYnew_list, Ymu_list, Yspace, kfold, bandwidths_mat, grids, weights, lambda_list, Xdim_max_list, R_list, index_mat, cv_type, penalty, gamma, degree, Kdenom_method, cv_const, max_cv_iter, threshold)
}

AM_CV_average <- function(SBF_comp, Xnew, LogYnew, Ymu, Yspace, lambda_list, Xdim_max_list, R_list, index_mat, cv_type = "AIC", penalty = "LASSO", gamma = 0, cv_const = 2.0, max_cv_iter = 20L, threshold = 1e-10) {
    .Call(`_HDRegMfd_AM_CV_average`, SBF_comp, Xnew, LogYnew, Ymu, Yspace, lambda_list, Xdim_max_list, R_list, index_mat, cv_type, penalty, gamma, cv_const, max_cv_iter, threshold)
}

AM_CV_integral <- function(SBF_comp, Xnew, LogYnew, Ymu, Yspace, lambda_list, Xdim_max_list, R_list, index_mat, cv_type = "AIC", penalty = "LASSO", gamma = 0, cv_const = 2.0, max_cv_iter = 20L, threshold = 1e-10) {
    .Call(`_HDRegMfd_AM_CV_integral`, SBF_comp, Xnew, LogYnew, Ymu, Yspace, lambda_list, Xdim_max_list, R_list, index_mat, cv_type, penalty, gamma, cv_const, max_cv_iter, threshold)
}

GLM_each <- function(Xorg, Yorg, lambda, Xdim_max, R, penalty, link, gamma, phi, eta, max_iter, threshold) {
    .Call(`_HDRegMfd_GLM_each`, Xorg, Yorg, lambda, Xdim_max, R, penalty, link, gamma, phi, eta, max_iter, threshold)
}

GLM_CV <- function(X, Y, lambda_list, Xdim_max_list, R_list, cv_type = "AIC", penalty = "LASSO", link = "binomial", gamma = 0, phi = 1, cv_const = 2.0, max_cv_iter = 20L, threshold = 1e-10) {
    .Call(`_HDRegMfd_GLM_CV`, X, Y, lambda_list, Xdim_max_list, R_list, cv_type, penalty, link, gamma, phi, cv_const, max_cv_iter, threshold)
}

GLM_GCV <- function(X, Y, Xnew, Ynew, lambda_list, Xdim_max_list, R_list, penalty = "LASSO", link = "binomial", gamma = 0, phi = 1, max_cv_iter = 20L, threshold = 1e-10) {
    .Call(`_HDRegMfd_GLM_GCV`, X, Y, Xnew, Ynew, lambda_list, Xdim_max_list, R_list, penalty, link, gamma, phi, max_cv_iter, threshold)
}

Link <- function(u, link) {
    .Call(`_HDRegMfd_Link`, u, link)
}

Inv_Link <- function(u, link) {
    .Call(`_HDRegMfd_Inv_Link`, u, link)
}

Psi <- function(u, link) {
    .Call(`_HDRegMfd_Psi`, u, link)
}

Psi_1d <- function(u, link) {
    .Call(`_HDRegMfd_Psi_1d`, u, link)
}

Psi_2d <- function(u, link) {
    .Call(`_HDRegMfd_Psi_2d`, u, link)
}

GLM_Kfold <- function(X_list, Y_list, Xnew_list, Ynew_list, kfold, lambda_list, Xdim_max_list, R_list, penalty = "LASSO", link = "binomial", gamma = 0, phi = 1, max_cv_iter = 20L, threshold = 1e-10) {
    .Call(`_HDRegMfd_GLM_Kfold`, X_list, Y_list, Xnew_list, Ynew_list, kfold, lambda_list, Xdim_max_list, R_list, penalty, link, gamma, phi, max_cv_iter, threshold)
}

normalized_Kernel <- function(X, bandwidths, grids, weights, degree, Kdenom_method) {
    .Call(`_HDRegMfd_normalized_Kernel`, X, bandwidths, grids, weights, degree, Kdenom_method)
}

KDE_ <- function(X, bandwidths, grids, weights, degree, Kdenom_method, is_proj) {
    .Call(`_HDRegMfd_KDE_`, X, bandwidths, grids, weights, degree, Kdenom_method, is_proj)
}

LM_each <- function(Xorg, LogY, Ymu, Yspace, lambda, Xdim_max, R, penalty, gamma, phi, eta, max_iter, threshold) {
    .Call(`_HDRegMfd_LM_each`, Xorg, LogY, Ymu, Yspace, lambda, Xdim_max, R, penalty, gamma, phi, eta, max_iter, threshold)
}

LM_CV <- function(X, LogY, Ymu, Yspace, lambda_list, Xdim_max_list, R_list, cv_type = "AIC", penalty = "LASSO", gamma = 0, phi = 1, cv_const = 2.0, max_cv_iter = 20L, threshold = 1e-10) {
    .Call(`_HDRegMfd_LM_CV`, X, LogY, Ymu, Yspace, lambda_list, Xdim_max_list, R_list, cv_type, penalty, gamma, phi, cv_const, max_cv_iter, threshold)
}

LM_GCV <- function(X, LogY, Xnew, LogYnew, Ymu, Yspace, lambda_list, Xdim_max_list, R_list, penalty = "LASSO", gamma = 0, phi = 1, max_cv_iter = 20L, threshold = 1e-10) {
    .Call(`_HDRegMfd_LM_GCV`, X, LogY, Xnew, LogYnew, Ymu, Yspace, lambda_list, Xdim_max_list, R_list, penalty, gamma, phi, max_cv_iter, threshold)
}

LM_Kfold <- function(X_list, LogY_list, Xnew_list, LogYnew_list, Ymu_list, Yspace, kfold, lambda_list, Xdim_max_list, R_list, penalty = "LASSO", gamma = 0, phi = 1, max_cv_iter = 20L, threshold = 1e-10) {
    .Call(`_HDRegMfd_LM_Kfold`, X_list, LogY_list, Xnew_list, LogYnew_list, Ymu_list, Yspace, kfold, lambda_list, Xdim_max_list, R_list, penalty, gamma, phi, max_cv_iter, threshold)
}

PCA_list <- function(Xall, alpha) {
    .Call(`_HDRegMfd_PCA_list`, Xall, alpha)
}

predict_PCA_list <- function(pca, Xnew) {
    .Call(`_HDRegMfd_predict_PCA_list`, pca, Xnew)
}

Penalty_ftn <- function(u, lambda_vec, penalty, gamma) {
    .Call(`_HDRegMfd_Penalty_ftn`, u, lambda_vec, penalty, gamma)
}

Penalty_diff_ftn <- function(u, lambda_vec, penalty, gamma) {
    .Call(`_HDRegMfd_Penalty_diff_ftn`, u, lambda_vec, penalty, gamma)
}

LASSO_sol <- function(xy, xx, normxy, lambda, kappa, gamma) {
    .Call(`_HDRegMfd_LASSO_sol`, xy, xx, normxy, lambda, kappa, gamma)
}

LASSO_sol2 <- function(xy, xx, normxy, lambda, kappa, gamma) {
    .Call(`_HDRegMfd_LASSO_sol2`, xy, xx, normxy, lambda, kappa, gamma)
}

SCAD_sol <- function(xy, xx, normxy, lambda, kappa, gamma) {
    .Call(`_HDRegMfd_SCAD_sol`, xy, xx, normxy, lambda, kappa, gamma)
}

SCAD_sol2 <- function(xy, xx, normxy, lambda, kappa, gamma) {
    .Call(`_HDRegMfd_SCAD_sol2`, xy, xx, normxy, lambda, kappa, gamma)
}

MCP_sol <- function(xy, xx, normxy, lambda, kappa, gamma) {
    .Call(`_HDRegMfd_MCP_sol`, xy, xx, normxy, lambda, kappa, gamma)
}

MCP_sol2 <- function(xy, xx, normxy, lambda, kappa, gamma) {
    .Call(`_HDRegMfd_MCP_sol2`, xy, xx, normxy, lambda, kappa, gamma)
}

QM_each <- function(Xorg, Yorg, lambda, Xdim_max, tau, h, kernel, penalty, gamma, phi0, c_phi, max_iter, threshold) {
    .Call(`_HDRegMfd_QM_each`, Xorg, Yorg, lambda, Xdim_max, tau, h, kernel, penalty, gamma, phi0, c_phi, max_iter, threshold)
}

QM_CV <- function(X, Y, lambda_list, Xdim_max_list, cv_type = "AIC", tau = 0.5, h = -1.0, kernel = "Gaussian", penalty = "LASSO", gamma = 0, cv_const = 2.0, max_cv_iter = 20L, threshold = 1e-10) {
    .Call(`_HDRegMfd_QM_CV`, X, Y, lambda_list, Xdim_max_list, cv_type, tau, h, kernel, penalty, gamma, cv_const, max_cv_iter, threshold)
}

QM_GCV <- function(X, Y, Xnew, Ynew, lambda_list, Xdim_max_list, tau = 0.5, h = -1.0, kernel = "Gaussian", penalty = "LASSO", gamma = 0, max_cv_iter = 20L, threshold = 1e-10) {
    .Call(`_HDRegMfd_QM_GCV`, X, Y, Xnew, Ynew, lambda_list, Xdim_max_list, tau, h, kernel, penalty, gamma, max_cv_iter, threshold)
}

sQRloss <- function(u, tau, h, kernel) {
    .Call(`_HDRegMfd_sQRloss`, u, tau, h, kernel)
}

sQRloss_diff <- function(u, tau, h, kernel) {
    .Call(`_HDRegMfd_sQRloss_diff`, u, tau, h, kernel)
}

QM_Kfold <- function(X_list, Y_list, Xnew_list, Ynew_list, kfold, lambda_list, Xdim_max_list, tau = 0.5, h = -1.0, kernel = "Gaussian", penalty = "LASSO", gamma = 0, max_cv_iter = 20L, threshold = 1e-10) {
    .Call(`_HDRegMfd_QM_Kfold`, X_list, Y_list, Xnew_list, Ynew_list, kfold, lambda_list, Xdim_max_list, tau, h, kernel, penalty, gamma, max_cv_iter, threshold)
}

SBF_preprocessing <- function(X, LogY, bandwidths, grids, weights, degree, Kdenom_method) {
    .Call(`_HDRegMfd_SBF_preprocessing`, X, LogY, bandwidths, grids, weights, degree, Kdenom_method)
}

SBF_preprocessing_reduce_dim <- function(SBF_comp, Xdim_max, index_mat) {
    .Call(`_HDRegMfd_SBF_preprocessing_reduce_dim`, SBF_comp, Xdim_max, index_mat)
}

multi_4d_ind_to_single <- function(j1, j2, k1, k2, p, g) {
    .Call(`_HDRegMfd_multi_4d_ind_to_single`, j1, j2, k1, k2, p, g)
}

single_ind_to_multi_4d <- function(j3, p, g) {
    .Call(`_HDRegMfd_single_ind_to_multi_4d`, j3, p, g)
}

multi_2d_ind_to_single_range <- function(j1, j2, p, g) {
    .Call(`_HDRegMfd_multi_2d_ind_to_single_range`, j1, j2, p, g)
}

multi_3d_ind_to_single_range <- function(j1, j2, k1, p, g) {
    .Call(`_HDRegMfd_multi_3d_ind_to_single_range`, j1, j2, k1, p, g)
}

numerical_integral_1d <- function(weights, func) {
    .Call(`_HDRegMfd_numerical_integral_1d`, weights, func)
}

numerical_integral_3d_to_2d <- function(weights, func) {
    .Call(`_HDRegMfd_numerical_integral_3d_to_2d`, weights, func)
}

numerical_integral_3d <- function(weights, func1, func2) {
    .Call(`_HDRegMfd_numerical_integral_3d`, weights, func1, func2)
}

numerical_integral_2d <- function(func1, func2) {
    .Call(`_HDRegMfd_numerical_integral_2d`, func1, func2)
}

