# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

LR_each <- function(Xorg, LogY, Ymu, inner, lambda, Xdim_max, R, phi, penalty, gamma, eta, max_iter, threshold) {
    .Call(`_NonEuclidReg_LR_each`, Xorg, LogY, Ymu, inner, lambda, Xdim_max, R, phi, penalty, gamma, eta, max_iter, threshold)
}

get_loss_LR <- function(X, LogY, Xnew_, LogYnew, Ymu, inner, lambda, Xdim_max, R, phi, penalty, gamma) {
    .Call(`_NonEuclidReg_get_loss_LR`, X, LogY, Xnew_, LogYnew, Ymu, inner, lambda, Xdim_max, R, phi, penalty, gamma)
}

LR_GCV <- function(X, LogY, Xnew, LogYnew, Ymu, inner, lambda_list, Xdim_max_list, R_list, phi = 1, penalty = "LASSO", gamma = 0, max_cv_iter = 20L, threshold = 1e-10) {
    .Call(`_NonEuclidReg_LR_GCV`, X, LogY, Xnew, LogYnew, Ymu, inner, lambda_list, Xdim_max_list, R_list, phi, penalty, gamma, max_cv_iter, threshold)
}

LR_Kfold <- function(X_list, LogY_list, Xnew_list, LogYnew_list, Ymu_list, inner, kfold, lambda_list, Xdim_max_list, R_list, phi = 1, penalty = "LASSO", gamma = 0, max_cv_iter = 20L, threshold = 1e-10) {
    .Call(`_NonEuclidReg_LR_Kfold`, X_list, LogY_list, Xnew_list, LogYnew_list, Ymu_list, inner, kfold, lambda_list, Xdim_max_list, R_list, phi, penalty, gamma, max_cv_iter, threshold)
}

PCA_list <- function(Xall) {
    .Call(`_NonEuclidReg_PCA_list`, Xall)
}

predict_PCA_list <- function(pca, Xnew) {
    .Call(`_NonEuclidReg_predict_PCA_list`, pca, Xnew)
}

LASSO_sol <- function(xy, xx, normxy, lambda, kappa, gamma) {
    .Call(`_NonEuclidReg_LASSO_sol`, xy, xx, normxy, lambda, kappa, gamma)
}

LASSO_sol2 <- function(xy, xx, normxy, lambda, kappa, gamma) {
    .Call(`_NonEuclidReg_LASSO_sol2`, xy, xx, normxy, lambda, kappa, gamma)
}

SCAD_sol <- function(xy, xx, normxy, lambda, kappa, gamma) {
    .Call(`_NonEuclidReg_SCAD_sol`, xy, xx, normxy, lambda, kappa, gamma)
}

SCAD_sol2 <- function(xy, xx, normxy, lambda, kappa, gamma) {
    .Call(`_NonEuclidReg_SCAD_sol2`, xy, xx, normxy, lambda, kappa, gamma)
}

MCP_sol <- function(xy, xx, normxy, lambda, kappa, gamma) {
    .Call(`_NonEuclidReg_MCP_sol`, xy, xx, normxy, lambda, kappa, gamma)
}

MCP_sol2 <- function(xy, xx, normxy, lambda, kappa, gamma) {
    .Call(`_NonEuclidReg_MCP_sol2`, xy, xx, normxy, lambda, kappa, gamma)
}

